Exception ignored in: <function CachingFileManager.__del__ at 0x7cd5f02f7f60>
Traceback (most recent call last):
  File "/mnt/c/Users/enlan/University/York/Dissertation/Repositories/Dissertation_Project/Misc/Test/blob2dgp/src/.venv/lib/python3.13/site-packages/xarray/backends/file_manager.py", line 250, in __del__
    self.close(needs_lock=False)
  File "/mnt/c/Users/enlan/University/York/Dissertation/Repositories/Dissertation_Project/Misc/Test/blob2dgp/src/.venv/lib/python3.13/site-packages/xarray/backends/file_manager.py", line 234, in close
    file.close()
  File "src/netCDF4/_netCDF4.pyx", line 2669, in netCDF4._netCDF4.Dataset.close